config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]
  resources :sound_groups, :only => [:index, :show, :new, :create, :destroy, :update]
  get '/sound_groups/:id/play', to: 'sound_groups#play'
  resources :tracks, :only => [:new, :create, :destroy]
  root to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sound_group.rb
class SoundGroup < ApplicationRecord

  validates :name, length: { minimum: 2, maximum: 20 }

  belongs_to :leader,
    primary_key: :id,
    foreign_key: :leader_id,
    class_name: :User,
    dependent: :destroy

  has_many :users,
    primary_key: :id,
    foreign_key: :sound_group_id,
    class_name: :User

end

app/models/track.rb
class Track < ApplicationRecord

  validates :name, length: { minimum: 1, maximum: 20 }

  has_many :sound_groups,
    primary_key: :id,
    foreign_key: :track_id,
    class_name: :SoundGroup

end

app/models/user.rb
class User < ApplicationRecord

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, length: { minimum: 2, maximum: 20 }

  has_one :sound_group_led,
    primary_key: :id,
    foreign_key: :leader_id,
    class_name: :SoundGroup

  after_initialize :ensure_session_token

  attr_reader :password

# exists for testing paper clip  "/images/:style/missing.png"
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
#  remove once out of dev.
  def self.find_by_credentials(username, pw)
    usr = User.find_by_username(username)
    return usr if usr && usr.is_password?(pw)
    nil
  end

  def is_password?(pw)
    digest = BCrypt::Password.new(self.password_digest)
    digest.is_password?(pw)
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :moderator?

  def log_in!(user)
    session[:session_token] = user.reset_token!
  end

  def log_out
    if logged_in?
      current_user.reset_token!
      current_user.sound_group_id = -1
      session[:session_token] = nil
    end
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to sound_groups_url if logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    require_logged_out
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password])
    if @user
      log_in!(@user)
      redirect_to sound_groups_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

app/controllers/sound_groups_controller.rb
class SoundGroupsController < ApplicationController

  before_action :require_logged_in

  def index
    current_user.sound_group_id = -1
    current_user.save
    @sound_groups = SoundGroup.all
  end

  def show
    current_user.sound_group_id = params[:id]
    @sound_group = SoundGroup.find(params[:id])
    current_user.save
    @users = @sound_group.users
    @tracks = Track.all
  end

  def new
    @sound_group = SoundGroup.new
  end

  def create
    @sound_group = SoundGroup.new(sound_group_params)
    if @sound_group.save
      current_user.sound_group_id = @sound_group
      redirect_to sound_group_url(@sound_group)
    else
      flash[:errors] = @sound_group.errors.full_messages
      redirect_to sound_groups_url
    end
  end

  def update
    @sound_group = SoundGroup.find(params[:id])
    @sound_group.update_attributes(sound_group_params)
    SoundGroupChannel.broadcast_to(@sound_group, track: {
    ch1: Track.find(params[:sound_group][:track_id]).channel1,
    ch2: Track.find(params[:sound_group][:track_id]).channel2,
    ch3: Track.find(params[:sound_group][:track_id]).channel3,
    ch4: Track.find(params[:sound_group][:track_id]).channel4,
    ch5: Track.find(params[:sound_group][:track_id]).channel5,
    })
    render json: {}
  end

  def play
    # p params
    @sound_group = SoundGroup.find(params[:id])
    SoundGroupChannel.broadcast_to(@sound_group, scheduled_time:
    params[:time] [:timestamp])
    render json: {}
  end

  def destroy
    @sound_group = SoundGroup.find(params[:id])
  end

  private

  def sound_group_params
    params.require(:sound_group).permit(:name, :leader_id, :track_id)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_logged_in

  def index
    @track = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    # p params[:track][:attachment].inspect
    # data = params[:track][:attachment].read
    # p params[:track][:data].inspect
    name = params[:track][:name]
    artist = params[:track][:artist]
    @track = Track.new(
      channel1: params[:track][:channel1],
      channel2: params[:track][:channel2],
      channel3: params[:track][:channel3],
      channel4: params[:track][:channel4],
      channel5: params[:track][:channel5],
      name: name,
      artist: artist)
    if @track.save
      redirect_to sound_groups_url
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
  end

  private

  def sound_group_params
    params.require(:track).permit(:name, :artist)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    require_logged_out
  end

  def create
    @user = User.new(user_params)
    @user.sound_group_id = -1
    if @user.save
      log_in!(@user)
      redirect_to :sound_groups
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sound_groups_helper.rb
module SoundGroupsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileSurround</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <div class='nav'>
      <div class = 'logo'>
        <img class='logo-img' src='https://res.cloudinary.com/dt3tnq8um/image/upload/c_scale,h_75,w_300/v1502472297/mobile_surround_logo_gkitds.png' />
      </div>
      <div class = 'nav-log'>
        <% if logged_in? %>
          <%= button_to "Sign Out", session_url, {class: 'sound-group-show-button', form_class: "sound-group-show-button-form", :method => :delete} %>
          <br><br>
          <%= button_to "Return Home", sound_groups_url, {class: 'sound-group-show-button', form_class: "sound-group-show-button-form", :method => :get} %>
        <% else %>
          <%= button_to "Log In", new_session_url,{class: 'sound-group-show-button', form_class: 'sound-group-show-button-form', :method => :get} %>
          <%= button_to "Sign Up", new_user_url, { class: 'sound-group-show-button', form_class: 'sound-group-show-button-form', :method => :get} %>
        <% end %>
      </div>
    </div>
    <div class = 'white-space'>
    </div>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/sound_groups/index.html.erb
<div class = 'sound-groups-index-container'>
  <!-- <div class = "location-service-access-request">
  </div> place this inside an existing div or the justify content space around will treat the empty div as an element to justify with. -->

  <div class = 'sound-group-list'>
    <li class="sound-group-list-item">
    <h4>Existing Sound Groups</h4>
    <br>
    </li>
    <% @sound_groups.each do |group| %>
      <li class="sound-group-list-item">
      <%= link_to group.name, sound_group_url(group) %>
      <br>
      </li>
    <% end %>
  </div>

  <div class = 'sound-group-container'>
    <%= flash[:errors] %>
    <br><br>
    <form action = "" method= 'POST' >
      <div>
        <label>Name of Sound Group:
          <br><br>
          <textarea value = "" name = 'sound_group[name]'
            placeholder="Input your Sound Group Name here." ></textarea>
            <br><br>
        </label>
      </div>

      <div class = 'sound-group-button' 'submit-button-container'>
        <input class = "submit-button" type="submit" value="New Sound Group">
      </div>

      <div>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
        <input type = "hidden" name = "sound_group[leader_id]" value = "<%= current_user.id %>" >
      </div>

    </form>
    <br><br><br>
    <div>
      <%= link_to "Create a new sound track link", new_track_url %>
    </div>
  </div>
</div>

app/views/sound_groups/show.html.erb
<script>
  function isMobileDevice() {
    return (typeof window.orientation !== "undefined") || (navigator.userAgent.indexOf('IEMobile') !== -1);
  };
  let GPS_TIME;
  if(isMobileDevice()) {GPS_TIME=false;}
  else {GPS_TIME=false;}
  $("<audio>")
   .on("canplaythrough", function () {
      // console.log("canplay event fire for dummy");
      this.pause();
      $(this).prependTo($("body"));
   })
  .attr("src", "https://freesound.org/data/previews/131/131660_2398403-lq.mp3")
  .attr("type", "audio/mpeg")
  .attr("id", "dummy")
  .attr("autoplay","");
  document.addEventListener("DOMContentLoaded", function(event) {
    localStorage.setItem('channel',"ch1");
    App.cable.subscriptions.create ({ channel: "SoundGroupChannel",
      id: "<%=current_user.sound_group_id%>"},{
        connected: () => {},
        disconnected: () =>{current_user.sound_group_id = -1
          App.cable.subscriptions.remove(this);},
        received: (info) => {
          let soundPlayer = document.getElementById('dummy');
          if(info.track){
            localStorage.setItem("ch1", info.track.ch1);
            localStorage.setItem("ch2", info.track.ch2);
            localStorage.setItem("ch3", info.track.ch3);
            localStorage.setItem("ch4", info.track.ch4);
            localStorage.setItem("ch5", info.track.ch5);
            // console.log(localStorage.getItem("channel"));
            // console.log(localStorage.getItem(info.track.ch5));
            // console.log(localStorage.getItem(localStorage.getItem("channel")));
            soundPlayer.src = localStorage.getItem(localStorage.getItem("channel"));
          }
          if(info.scheduled_time)
          {
            scheduled_time=info.scheduled_time;
            // let soundPlayer = document.getElementById('sound-player');


            // soundPlayer.muted=false;
            // soundPlayer.currentTime = 0.0;
            soundPlayer.play();
            // console.log(soundPlayer);
            scheduled_time = parseInt(scheduled_time)+500;
            // console.log("received play message from server, scheduled time: "+scheduled_time);
            if(GPS_TIME){
              window.navigator.geolocation.getCurrentPosition((time) => {
                time=parseInt(time.timestamp);
                // console.log("GPS time: "+time);
                // console.log("delta: "+(scheduled_time-time));
                // setTimeout(()=>{soundPlayer.play();}, scheduled_time-time);
              });
            }else{
              time=parseInt(new Date().getTime());
              // console.log("Clock time: "+time);
              // console.log("delta: "+(scheduled_time-time));
              // setTimeout(()=>{soundPlayer.play();}, scheduled_time-time);
            }
          }
        }
     });
   });
</script>

<div class = 'sound-group-show-container' >
  <!-- <div class = 'members'>
    <label>Members:
      <br><br>
      <div class = 'subscribed-users'>
        <% @users.each do |user| %>
          <%= user.username %>
          <br><br>
        <% end %>
      </div>
    </label>
    <br><br> -->
    <%= link_to "leave group", sound_groups_url %>
  </div>


  <div class = 'music-player'>

    <!-- mp3-downloads/Toccata-and-Fugue-Dm.mp3 -->
    <div class="sound-controls">
      <!-- This is just a testing tool; remove in final build -->
      <button onClick=
        "let dummy = document.getElementById('dummy');
        dummy.play();"
        >Test sound on my device</button>
        <div class = 'speaker-arrangement'>
          <label>Step 1: Each user picks a different channel here
            <select name="channel-picker" onchange="
            localStorage.setItem('channel', this.value);">
              <option value="ch1">1</option>
              <option value="ch2">2</option>
              <option value="ch3">3</option>
              <option value="ch4">4</option>
              <option value="ch5">5</option>
            </select>
          </label>
          <label>Step 2: One user picks a song here
          <% if current_user.id == @sound_group.leader.id || true %>
          <select name="tracklist" onchange="
          $.ajax({
          url: '<%=current_user.sound_group_id%>',
          data: {sound_group: {track_id: this.value}},
          method: 'patch'
          });
          ">
            <option value="-1"></option>
            <% @tracks.each do |track| %>
              <option value="<%=track.id%>"><%=track.name%>:<%=track.artist%></option>
            <% end %>
          </select>
          </label>
          <% else  %>
            <h5>Sound Group Leader will determine the song. </h5>
          <% end %>
        </div>
        <button onClick=
        "let dummy = document.getElementById('dummy');
        dummy.play();
        dummy.src=localStorage.getItem(localStorage.getItem('channel'));
        ">Step 3: Mobile users click this to preload sound, then wait to load</button>
      <!-- This is the real button. Move it to leader-only in final build? -->
      <button onClick="if(GPS_TIME){
          window.navigator.geolocation.getCurrentPosition((time) =>
          {
            $.ajax({url: '<%=current_user.sound_group_id%>/play', data: {time: time}})});
        }
        else
        {
          let time=new Date().getTime();
          $.ajax({url: '<%=current_user.sound_group_id%>/play', data: {time: {timestamp: time}}});
        }"
        >Step 4: Once mobile loading finishes, one user clicks this to play!</button>
    </div>



  </div>






</div>

app/views/tracks/new.html.erb
<div class = "track-upload-container">
  <h4>Upload Track</h4>
  <%= flash[:errors] %>
  <%= form_for @track, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :artist %>
      <%= f.text_field :artist %>
      <%= f.label :url1 %>
      <%= f.text_field :channel1 %>
      <%= f.label :url2 %>
      <%= f.text_field :channel2 %>
      <%= f.label :url3 %>
      <%= f.text_field :channel3 %>
      <%= f.label :url4 %>
      <%= f.text_field :channel4 %>
      <%= f.label :url5 %>
      <%= f.text_field :channel5 %>
      <br>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/tracks/show.html.erb
<audio id="<%= @track.id %>" controls>
  <source src="<%= stream_path(@track.id) %>"></source>
</audio>

app/views/users/new.html.erb
<div class="new-user-container">
  <div class= 'new-user-form' >

    <br>
    <%= flash[:errors] %>
    <h2>Create a Mobile Surround Account!</h2>
    <br>
    <%= flash[:errors] %>
    <br>
    <form action="<%=users_url%>" method="POST">
      <div class="">
        <label > Username:
          <input type="text" name="user[username]" value="" >
        </label>
      </div>
      <br>
      <div class="password-container">
        <label for="password"> Password: </label>
        <input id="password" type="password" name="user[password]" value=""
        placeholder="at least 6 characters">
      </div>
      <div class="submit-button-container">
        <input class="submit-button" type="submit" value="Sign Up">
      </div>
        <input type="hidden" name="authenticity_token"
        value="<%= form_authenticity_token %>">
    </form>
  </div>
</div>